### PR TITLE
multi-image support

### PR DESCRIPTION
**Pull request by mlos**
Hello Richard,

As mentioned in the luma.core pull request, this demo shows the usage of multiimage.py, by providing scrolling images (rendered text with artist + song info)

Best regards,
 Maarten

### CODE REVIEW

**Comment by mlos** [comment]
Hi,

I'd like to submit the ImageComposition companion demo for review as well.

Note that Travis fails on Python 3.5, but this is due to included dependencies - it's not caused by image_composition_demo.py

https://travis-ci.org/rm-hull/luma.examples/jobs/293317507

Best regards,
 Maarten

**Comment by thijstriemstra** [comment]
> Note that Travis fails on Python 3.5, but this is due to included dependencies - it's not caused by image_composition_demo.py

Good point, I opened PR #64 for that.

**Comment by thijstriemstra** [comment]
This PR is blocked until https://github.com/rm-hull/luma.core/pull/102 lands and is released. Once it does we should also bump the luma.core required version in setup.py of this repository.

**Comment by mlos** [comment]
Hi, just updated the README

**Comment by thijstriemstra** [comment]
version nr still needs to bumped in setup.py.

**Pull request merged**
