### PR TITLE
update test for luma.core >= 0.5.42 and luma.lcd >= 0.3.2

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
This is blocked by new luma.lcd release.

**Comment by thijstriemstra** [comment]
one of the failing tests is comparing an incorrect error message, should be 'error: GPIO access not available'. Other one is still not clear to me why it fails.

**Comment by thijstriemstra** [comment]
Perhaps led_matrix also needs to be updated, investigating.

**Comment by thijstriemstra** [comment]
So the test I updated now fails with: `RuntimeError: Module not imported correctly!` which is interesting, where does this error come from.

**Comment by rm-hull** [comment]
I think that RPi.GPIO is horrendously stateful, if you import it once you get one error, call it again a second time after it has already barfed, you get a different error

**Comment by thijstriemstra** [comment]
The error is from RPi.GPIO indeed: https://sourceforge.net/p/raspberry-gpio-python/code/ci/default/tree/source/py_gpio.c#l254 So luma.core will also have to catch that error and we'll need a new release. Working on PR.

**Comment by thijstriemstra** [comment]
@rm-hull I think we're running into the same issue; the class `spi`'s constructions accepts a `spi` argument and they clash.. The [test failure](https://travis-ci.org/rm-hull/luma.examples/jobs/209100228):

```
self = <luma.core.serial.spi object at 0x7f579f8e3710>, spi = None

gpio = <luma.core.serial.noop object at 0x7f57a511f978>, port = 0, device = 0

bus_speed_hz = 8000000, transfer_size = 4096, bcm_DC = 24, bcm_RST = 25

    def __init__(self, spi=None, gpio=None, port=0, device=0,

                 bus_speed_hz=8000000, transfer_size=4096,

                 bcm_DC=24, bcm_RST=25):

        assert(bus_speed_hz in [mhz * 1000000 for mhz in [0.5, 1, 2, 4, 8, 16, 32]])

        self._gpio = gpio or self.__rpi_gpio__()

>       self._spi = spi or self.__spidev__()

E       AttributeError: 'spi' object has no attribute '__spidev__'
```

Otherwise I would expect this error to say `None object has no attribute '__spidev__' but I could be wrong..

**Comment by thijstriemstra** [comment]
I can't reproduce the issue locally..

**Comment by rm-hull** [comment]
I can't really understand why thats failing. 
Alternatively, could the decorators be implemented as mixins instead?

**Comment by thijstriemstra** [comment]
@rm-hull yea but I find them more useful as decorators so I can re-use them as well. Still investigating but let's hold off on new luma.core release till this is fixed.

**Comment by thijstriemstra** [comment]
think i found the issue, creating PR for core now.

**Comment by thijstriemstra** [comment]
So it's only failing for python2.7 :-/

**Pull request merged**
