### PR TITLE
update help output

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs #96

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@rm-hull I also want to update the command-line help output in the README.rst but don't have a linux machine at hand where I can run the command. Could you add that to this PR?

**Comment by thijstriemstra** [comment]
@rm-hull this does not look like the latest cmdline output, are you sure latest luma.core is installed?

**Comment by rm-hull** [comment]
Ah, good catch ... it was 1.8.1

**Comment by thijstriemstra** [comment]
@rm-hull you'll have to install all luma libraries to get the correct output. Looks like there's also an old luma.oled present for example, many devices are missing.

**Comment by thijstriemstra** [comment]
@rm-hull added a help call to tox script so we can copy/paste it from travis output in the future. This PR should be ok now.

**Pull request merged**
