### PR TITLE
add cmdline module

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs https://github.com/rm-hull/luma.core/issues/58

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Eventually I'd like to move this module into a separate package so it can be reused by other projects. Something like luma.cmdline? Thoughts @rm-hull?

**Comment by rm-hull** [comment]
Yeah, i think so... I think it could (should?) live in luma.core

**Comment by thijstriemstra** [comment]
ok i'll move it into core.

**Comment by rm-hull** [comment]
into `luma.core.util` maybe ?

Can the code in `luma.core.lib` be lumped into util too (if that is appropriate?)

**Pull request merged**
